//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class product_recommendation_data_supermarket {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal product_recommendation_data_supermarket() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.product_recommendation_data_supermarket", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://supermarket.kibrisorder.com/en/chicken-flavoured-indomie-2.
        /// </summary>
        internal static string product_1_buy_now_link {
            get {
                return ResourceManager.GetString("product_1_buy_now_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ₺.
        /// </summary>
        internal static string product_1_currency_symbol {
            get {
                return ResourceManager.GetString("product_1_currency_symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://supermarket.kibrisorder.com/images/thumbs/0001463_chicken-flavoured-indomie.jpeg.
        /// </summary>
        internal static string product_1_image_url {
            get {
                return ResourceManager.GetString("product_1_image_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1,50.
        /// </summary>
        internal static string product_1_price {
            get {
                return ResourceManager.GetString("product_1_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chicken Flavoured Indomie.
        /// </summary>
        internal static string product_1_product_name {
            get {
                return ResourceManager.GetString("product_1_product_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://supermarket.kibrisorder.com/en/nutella-750g.
        /// </summary>
        internal static string product_2_buy_now_link {
            get {
                return ResourceManager.GetString("product_2_buy_now_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ₺.
        /// </summary>
        internal static string product_2_currency_symbol {
            get {
                return ResourceManager.GetString("product_2_currency_symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://supermarket.kibrisorder.com/images/thumbs/0001685_nutella-750g.jpeg.
        /// </summary>
        internal static string product_2_image_url {
            get {
                return ResourceManager.GetString("product_2_image_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20,99.
        /// </summary>
        internal static string product_2_price {
            get {
                return ResourceManager.GetString("product_2_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nutella 750g.
        /// </summary>
        internal static string product_2_product_name {
            get {
                return ResourceManager.GetString("product_2_product_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://supermarket.kibrisorder.com/en/dankek-lokmal%C4%B1k-havu%C3%A7lu-tar%C3%A7%C4%B1nl%C4%B1.
        /// </summary>
        internal static string product_3_buy_now_link {
            get {
                return ResourceManager.GetString("product_3_buy_now_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ₺.
        /// </summary>
        internal static string product_3_currency_symbol {
            get {
                return ResourceManager.GetString("product_3_currency_symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://supermarket.kibrisorder.com/images/thumbs/0001686_dankek-lokmalik-havuclu-tarcinli.jpeg.
        /// </summary>
        internal static string product_3_image_url {
            get {
                return ResourceManager.GetString("product_3_image_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4,75.
        /// </summary>
        internal static string product_3_price {
            get {
                return ResourceManager.GetString("product_3_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dankek Lokmalık Havuçlu Tarçınlı.
        /// </summary>
        internal static string product_3_product_name {
            get {
                return ResourceManager.GetString("product_3_product_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://supermarket.kibrisorder.com/en/fru-fresh-uskumru-mackerel.
        /// </summary>
        internal static string product_4_buy_now_link {
            get {
                return ResourceManager.GetString("product_4_buy_now_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ₺.
        /// </summary>
        internal static string product_4_currency_symbol {
            get {
                return ResourceManager.GetString("product_4_currency_symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://supermarket.kibrisorder.com/images/thumbs/0002182_fru-fresh-uskumru-mackerel.jpeg.
        /// </summary>
        internal static string product_4_image_url {
            get {
                return ResourceManager.GetString("product_4_image_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 19,99.
        /// </summary>
        internal static string product_4_price {
            get {
                return ResourceManager.GetString("product_4_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fru Fresh Uskumru (Mackerel).
        /// </summary>
        internal static string product_4_product_name {
            get {
                return ResourceManager.GetString("product_4_product_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://supermarket.kibrisorder.com/en/superfresh-garnish-canned-food-2.
        /// </summary>
        internal static string product_5_buy_now_link {
            get {
                return ResourceManager.GetString("product_5_buy_now_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ₺.
        /// </summary>
        internal static string product_5_currency_symbol {
            get {
                return ResourceManager.GetString("product_5_currency_symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://supermarket.kibrisorder.com/images/thumbs/0001341_superfresh-garnish-canned-food.jpeg.
        /// </summary>
        internal static string product_5_image_url {
            get {
                return ResourceManager.GetString("product_5_image_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14,00.
        /// </summary>
        internal static string product_5_price {
            get {
                return ResourceManager.GetString("product_5_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SuperFresh Garnish Canned Food.
        /// </summary>
        internal static string product_5_product_name {
            get {
                return ResourceManager.GetString("product_5_product_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://supermarket.kibrisorder.com/en/bruggen-corn-flakes-375g.
        /// </summary>
        internal static string product_6_buy_now_link {
            get {
                return ResourceManager.GetString("product_6_buy_now_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ₺.
        /// </summary>
        internal static string product_6_currency_symbol {
            get {
                return ResourceManager.GetString("product_6_currency_symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://supermarket.kibrisorder.com/images/thumbs/0001683_bruggen-corn-flakes-375g.jpeg.
        /// </summary>
        internal static string product_6_image_url {
            get {
                return ResourceManager.GetString("product_6_image_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9,50.
        /// </summary>
        internal static string product_6_price {
            get {
                return ResourceManager.GetString("product_6_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bruggen Corn flakes 375g.
        /// </summary>
        internal static string product_6_product_name {
            get {
                return ResourceManager.GetString("product_6_product_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prices you’ll love.
        /// </summary>
        internal static string section_header_main_text {
            get {
                return ResourceManager.GetString("section_header_main_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPECTACULAR KIBRIS ORDER SALES.
        /// </summary>
        internal static string section_header_text {
            get {
                return ResourceManager.GetString("section_header_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy now.
        /// </summary>
        internal static string shared_buy_now_button {
            get {
                return ResourceManager.GetString("shared_buy_now_button", resourceCulture);
            }
        }
    }
}
